### ISSUE TITLE
still using them?

### ISSUE THREAD

**Issue by yarikoptic** [Stebalien/msmtp-queue#7]
just wondering before adopting since seems exactly what I need but wondered if there is anything "better" you might have replaced them with?

**Comment by Stebalien** [comment]
I'm still using these. I believe upstream's version has been improved since I last checked so I'd recommend you check that first. But this one works for me so I haven't checked.

**Comment by yarikoptic** [comment]
oh, where is upstream? I see no reflection in README and this is not marked as fork on github.  But I could be blind

**Comment by Stebalien** [comment]
Sorry, I mean upstream msmtp:

- https://github.com/marlam/msmtp/tree/master/scripts/msmtpq
- https://github.com/marlam/msmtp/tree/master/scripts/msmtpqueue

(the first one looks better maintained)
